<?php 

/*
|------------------------------------------------------------------------
| Lenevor Config File Map                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build filemap. 
|
| Note: [!!] Do not modify it directly.
|
*/
return [

    '256f4ee8a901bd923c73' => SYS_PATH.'src/classes/Core/helpers.php',
    '09454abasdsdcd864721' => SYS_PATH.'src/classes/Collections/helpers.php',
    '102ba5d118e42f3abd85' => SYS_PATH.'src/classes/Support/helpers.php',
        
];