<?php 

/**
 * Lenevor Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file license.md.
 * It is also available through the world-wide-web at this URL:
 * https://lenevor.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Lenevor.com so we can send you a copy immediately.
 *
 * @package     Lenevor
 * @subpackage  Base
 * @link        https://lenevor.com
 * @copyright   Copyright (c) 2019 - 2026 Alexander Campo <jalexcam@gmail.com>
 * @license     https://opensource.org/licenses/BSD-3-Clause New BSD license or see https://lenevor.com/license or see /license.md
 */

namespace Syscodes\Components\Database\Connections;

use Exception;
use PDO;
use Syscodes\Components\Database\Query\Grammars\MySqlGrammar as QueryGrammar;
use Syscodes\Components\Database\Query\Processors\MySqlProcessor as QueryProcessor;
use Syscodes\Components\Database\Schema\Builders\MySqlBuilder;
use Syscodes\Components\Database\Schema\Grammars\MySqlGrammar as SchemaGrammar;

/**
 * Mysql connection.
 */
class MySqlConnection extends Connection
{
    /**
     * The last inserted ID generated by the server.
     * 
     * @var string|int|null
     */
    protected $lastInsertId;

    /**
     * {@inheritdoc}
     */
    public function getDriverTitle()
    {
        return $this->isMaria() ? 'MariaDB' : 'MySQL';
    }
    
    /**
     * Run an insert statement against the database.
     *
     * @param  string  $query
     * @param  array  $bindings
     * @param  string|null  $sequence
     * 
     * @return bool
     */
    public function insert(string $query, array $bindings = [], $sequence = null): bool
    {
        return $this->run($query, $bindings, function ($query, $bindings) use ($sequence) {
            if ($this->pretending()) {
                return true;
            }

            $statement = $this->getPdo()->prepare($query);

            $this->bindValues($statement, $this->prepareBindings($bindings));

            $result = $statement->execute();

            $this->lastInsertId = $this->getPdo()->lastInsertId($sequence);

            return $result;
        });
    }
    
    /**
     * Determine if the given database exception was caused by a unique constraint violation.
     * 
     * @param  \Exception  $exception
     * 
     * @return bool
     */
    protected function isConstraintError(Exception $exception)
    {
        return (bool) preg_match('#Integrity constraint violation: 1062#i', $exception->getMessage());
    }

    /**
     * Get the connection's last insert ID.
     *
     * @return string|int|null
     */
    public function getLastInsertId()
    {
        return $this->lastInsertId;
    }
    
    /**
     * Determine if the connected database is a MariaDB database.
     * 
     * @return bool
     */
    public function isMaria(): bool
    {
        return str_contains($this->getPdo()->getAttribute(PDO::ATTR_SERVER_VERSION), 'MariaDB');
    }

    /**
     * Get the default query grammar instance.
     * 
     * @return \Syscodes\Components\Database\Query\Grammars\MySqlGrammar
     */
    public function getDefaultQueryGrammar()
    {
        return $this->withTablePrefix(new QueryGrammar);
    }

    /**
     * Get the default post processor instance.
     * 
     * @return \Syscodes\Components\Database\Query\Processors\MySqlProcessor
     */
    public function getDefaultPostProcessor()
    {
        return new QueryProcessor;
    }

    /**
     * Get a schema builder instance for the connection.
     *
     * @return \Syscodes\Components\Database\Schema\Builders\MySqlBuilder
     */
    public function getSchemaBuilder()
    {
        if (is_null($this->schemaGrammar)) {
            $this->useDefaultSchemaGrammar();
        }

        return new MySqlBuilder($this);
    }

    /**
     * Get the default schema grammar instance.
     *
     * @return \Syscodes\Components\Database\Schema\Grammars\MySqlGrammar
     */
    protected function getDefaultSchemaGrammar()
    {
        return $this->withTablePrefix(new SchemaGrammar);
    }
}