<?php

/**
 * Lenevor Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file license.md.
 * It is also available through the world-wide-web at this URL:
 * https://lenevor.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Lenevor.com so we can send you a copy immediately.
 *
 * @package     Lenevor
 * @subpackage  Base
 * @link        https://lenevor.com
 * @copyright   Copyright (c) 2019 - 2026 Alexander Campo <jalexcam@gmail.com>
 * @license     https://opensource.org/licenses/BSD-3-Clause New BSD license or see https://lenevor.com/license or see /license.md
 */

namespace Syscodes\Components\Routing\Generators;

use Closure;
use InvalidArgumentException;
use Syscodes\Components\Contracts\Routing\UrlGenerator as UrlGeneratorContract;
use Syscodes\Components\Contracts\Routing\UrlRoutable;
use Syscodes\Components\Http\Request;
use Syscodes\Components\Routing\Collections\RouteCollection;
use Syscodes\Components\Routing\RouteUrlGenerator;
use Syscodes\Components\Support\Arr;
use Syscodes\Components\Support\Chronos;
use Syscodes\Components\Support\Collection;
use Syscodes\Components\Support\Str;
use Syscodes\Components\Support\Traits\Macroable;

/**
 * Returns the URL generated by the user.
 */
class UrlGenerator implements UrlGeneratorContract
{
    use Macroable;

    /**
     * The asset root URL.
     *
     * @var string
     */
    protected $assetRoot;

    /**
     * A cached copy of the URL root for the current request.
     * 
     * @var string|null
     */
    protected $cachedRoot;
    
    /**
     * A cached copy of the URL scheme for the current request.
     * 
     * @var string|null
     */
    protected $cachedScheme;

    /**
     * The force URL root.
     * 
     * @var string 
     */
    protected $forcedRoot;

    /**
     * The force Scheme for URLs.
     * 
     * @var string
     */
    protected $forcedScheme;

    /**
     * The callback to use to format hosts.
     *
     * @var \Closure
     */
    protected $formatHostUsing;

    /**
     * The callback to use to format paths.
     *
     * @var \Closure
     */
    protected $formatPathUsing;
    
    /**
     * The encryption key resolver callable.
     * 
     * @var callable
     */
    protected $keyResolver;

    /**
     * The Request instance.
     * 
     * @var \Syscodes\Components\Http\Request
     */
    protected $request;
    
    /**
     * The root namespace being applied to controller actions.
     * 
     * @var string
     */
    protected $rootNamespace;
    
    /**
     * The route URL generator instance.
     * 
     * @var \Syscodes\Components\Routing\Generators\RouteUrlGenerator|null
     */
    protected $routeGenerator;

    /**
     * The route collection.
     * 
     * @var \Syscodes\Components\Routing\Collections\RouteCollection
     */
    protected $routes;
    
    /**
     * The session resolver callable.
     * 
     * @var callable
     */
    protected $sessionResolver;

    /**
     * Constructor. The UrlGenerator class instance.
     * 
     * @param  \Syscodes\Components\Routing\Collections\RouteCollection  $route
     * @param  \Syscodes\Components\Http\Request  $request
     * @param  string|null  $assetRoot 
     * @return void
     */
    public function __construct(RouteCollection $route, Request $request, $assetRoot = null)
    {
        $this->routes = $route;
        $this->assetRoot = $assetRoot;

        $this->setRequest($request);
    }
    
    /**
     * Get the full URL for the current request.
     * 
     * @return string
     */
    public function full(): string
    {
        return $this->request->fullUrl();
    }

    /**
     * Get the current URL for the request.
     * 
     * @return string
     */
    public function current(): string
    {
        return $this->to($this->request->getPathInfo());
    }

    /**
     * Get the URL for the previous request.
     * 
     * @param  mixed  $fallback 
     * @return string
     */
    public function previous($fallback = false): string
    {
        $referer = $this->request->referer();

        $url = $referer ? $this->to($referer) : $this->getPreviousUrlSession();

        if ($url) {
            return $url;
        } elseif ($fallback) {
            return $this->to($fallback);
        }

        return $this->to('/');
    }
    
    /**
     * Get the previous URL from the session if possible.
     * 
     * @return string|null
     */
    protected function getPreviousUrlSession(): string|null
    {
        $session = $this->getSession();
        
        return $session ? $session->previousUrl() : null;
    }

    /**
     * Generate a absolute URL to the given path.
     * 
     * @param  string  $path
     * @param  mixed  $options
     * @param  bool|null  $secure 
     * @return string
     */
    public function to($path, $options = [], $secure = null): string
    {
        // First we will check if the URL is already a valid URL. If it is we will not
        // try to generate a new one but will simply return the URL as is, which is
        // convenient since developers do not always have to check if it's valid.
        if ($this->isValidUrl($path)) {
            return $path;
        }

        $tail = implode('/', array_map(
            'rawurlencode', (array) $this->formatParameters($options))
        );

        $scheme = $this->formatScheme($secure);

        $root = $this->formatRoot($scheme);

        [$path, $query] = $this->extractQueryString($path);

        return $this->format(
            $root, '/'.trim($path.'/'.$tail, '/')
        ).$query;
    }

    /**
     * Generate a secure, absolute URL to the given path.
     * 
     * @param  string  $path
     * @param  array  $parameters 
     * @return string
     */
    public function secure($path, $parameters = []): string
    {
        return $this->to($path, $parameters, true);
    }

    /**
     * Generate an absolute URL with the given query parameters.
     *
     * @param  string  $path
     * @param  array  $query
     * @param  mixed  $options
     * @param  bool|null  $secure
     * @return string
     */
    public function query($path, $query = [], $options = [], $secure = null): string
    {
        [$path, $existingQueryString] = $this->extractQueryString($path);

        parse_str(Str::after($existingQueryString, '?'), $existingQueryArray);

        return rtrim($this->to($path.'?'.Arr::query(
            array_merge($existingQueryArray, $query)
        ), $options, $secure), '?');
    }

    /**
     * Generate a URL to an application asset.
     * 
     * @param  string  $path
     * @param  bool|null  $secure 
     * @return string
     */
    public function asset($path, $secure = null): string
    {
        if ($this->isValidUrl($path)) {
            return $path;
        }

        // Once we get the root URL, we will check to see if it contains an index.php
        // file in the paths. If it does, we will remove it since it is not needed
        // for asset paths, but only for routes to endpoints in the application.
        $root = $this->assetRoot ?: $this->formatRoot($this->formatScheme($secure));

        return Str::finish($this->removeIndex($root), '/').trim($path, '/');
    }
    
    /**
     * Generate a URL to a secure asset.
     * 
     * @param  string  $path 
     * @return string
     */
    public function secureAsset($path): string
    {
        return $this->asset($path, true);
    }

    /**
     * Remove the index.php file from a path.
     * 
     * @param  string  $root 
     * @return string
     */
    protected function removeIndex($root): string
    {
        $index = 'index.php';

        return Str::contains($root, $index) ? str_replace('/'.$index, '', $root) : $root;
    }

    /**
     * Force the scheme for URLs.
     * 
     * @param  string  $scheme 
     * @return void
     */
    public function forceScheme($scheme): void
    {
        $this->cachedScheme = null;

        $this->forcedScheme = $scheme ? $scheme.'://' : null; 
    }

    /**
     * Force the use of the HTTPS scheme for all generated URLs.
     *
     * @param  bool  $force
     * @return void
     */
    public function forceHttps($force = true)
    {
        if ($force) {
            $this->forceScheme('https');
        }
    }

    /**
     * Determine if the given request has a valid signature.
     *
     * @param  \Syscodes\Components\Http\Request  $request
     * @param  bool  $absolute
     * @param  \Closure|array  $ignoreQuery 
     * @return bool
     */
    public function hasValidSignature(Request $request, $absolute = true, Closure|array $ignoreQuery = []): bool
    {
        return $this->hasCorrectSignature($request, $absolute, $ignoreQuery)
            && $this->signatureHasNotExpired($request);
    }

    /**
     * Determine if the given request has a valid signature for a relative URL.
     *
     * @param  \Syscodes\Components\Http\Request  $request
     * @param  \Closure|array  $ignoreQuery 
     * @return bool
     */
    public function hasValidRelativeSignature(Request $request, Closure|array $ignoreQuery = []): bool
    {
        return $this->hasValidSignature($request, false, $ignoreQuery);
    }

    /**
     * Determine if the signature from the given request matches the URL.
     *
     * @param  \Syscodes\Components\Http\Request  $request
     * @param  bool  $absolute
     * @param  \Closure|array  $ignoreQuery 
     * @return bool
     */
    public function hasCorrectSignature(Request $request, $absolute = true, Closure|array $ignoreQuery = []): bool
    {
        $url = $absolute ? $request->url() : '/'.$request->path();

        $queryString = (new Collection(explode('&', (string) $request->server->get('QUERY_STRING'))))
            ->reject(function ($parameter) use ($ignoreQuery) {
                $parameter = Str::before($parameter, '=');

                if ($parameter === 'signature') {
                    return true;
                }

                if ($ignoreQuery instanceof Closure) {
                    return $ignoreQuery($parameter);
                }

                return in_array($parameter, $ignoreQuery);
            })
            ->join('&');

        $original = rtrim($url.'?'.$queryString, '?');

        $keys = call_user_func($this->keyResolver);

        $keys = is_array($keys) ? $keys : [$keys];

        foreach ($keys as $key) {
            if (hash_equals(
                hash_hmac('sha256', $original, $key),
                (string) $request->query('signature', '')
            )) {
                return true;
            }
        }

        return false;
    }

    /**
     * Determine if the expires timestamp from the given request is not from the past.
     *
     * @param  \Syscodes\Components\Http\Request  $request 
     * @return bool
     */
    public function signatureHasNotExpired(Request $request): bool
    {
        $expires = $request->query('expires');

        return ! ($expires && Chronos::getTimestamp() > $expires);
    }

    /**
     * Get the URL to a named route.
     * 
     * @param  string  $name
     * @param  array  $parameters
     * @param  bool  $forced 
     * @return string
     * 
     * @throws \InvalidArgumentException
     */
    public function route($name, array $parameters = [], $forced = true): string
    {
        if ( ! is_null($route = $this->routes->getByName($name))) {
            return $this->toRoute($route, $parameters, $forced);
        }

        throw new InvalidArgumentException("Route [{$name}] not defined");
    }

    /**
     * Get the URL for a given route instance.
     * 
     * @param  \Syscodes\Components\Routing\Route  $route
     * @param  mixed  $parameters
     * @param  bool  $forced 
     * @return string
     */
    public function toRoute($route, $parameters, $forced): string
    {
        return $this->routeUrl()->to(
            $route, $parameters, $forced
        );
    }
    
    /**
     * Get the URL to a controller action.
     * 
     * @param  string  $action
     * @param  mixed  $parameters
     * @param  bool  $forced 
     * @return string
     * 
     * @throws \InvalidArgumentException
     */
    public function action($action, $parameters = [], $forced = true): string
    {
        if (is_null($route = $this->routes->getByAction($action = $this->formatAction($action)))) {
            throw new InvalidArgumentException("Action {$action} not defined");
        }
        
        return $this->toRoute($route, $parameters, $forced);
    }

    /**
     * Extract the query string from the given path.
     *
     * @param  string  $path
     * @return array
     */
    protected function extractQueryString($path): array
    {
        if (($queryPosition = strpos($path, '?')) !== false) {
            return [
                substr($path, 0, $queryPosition),
                substr($path, $queryPosition),
            ];
        }

        return [$path, ''];
    }

    /**
     * Get the scheme for a raw URL.
     * 
     * @param  bool|null  $secure 
     * @return string
     */
    public function formatScheme($secure = null): string
    {
        if ( ! is_null($secure)) {
            return $secure ? 'https://' : 'http://';
        }

        if (is_null($this->cachedScheme)) {
            $this->cachedScheme = $this->forcedScheme ?: $this->request->getScheme().'://';
        }

        return $this->cachedScheme;
    }
    
    /**
     * Format the given controller action.
     * 
     * @param  string|array  $action 
     * @return string
     */
    protected function formatAction($action): string
    {
        if (is_array($action)) {
            $action = '\\'.implode('@', $action);
        }
        
        if ($this->rootNamespace && ! str_starts_with($action, '\\')) {
            return $this->rootNamespace.'\\'.$action;
        }
        
        return trim($action, '\\');
    }
    
    /**
     * Format the array of URL parameters.
     * 
     * @param  mixed  $parameters 
     * @return array
     */
    public function formatParameters($parameters): array
    {
        $parameters = Arr::wrap($parameters);
        
        foreach ($parameters as $key => $parameter) {
            if ($parameter instanceof UrlRoutable) {
                $parameters[$key] = $parameter->getRouteKey();
            }
        }
        
        return $parameters;
    }
    
    /**
     * Get the base URL for the request.
     * 
     * @param  string  $scheme
     * @param  string|null  $root 
     * @return string
     */
    public function formatRoot($scheme, $root = null): string
    {
        if (is_null($root)) {
            if (is_null($this->cachedRoot)) {
                $this->cachedRoot = $this->forcedRoot ?: $this->request->root();
            }

            $root = $this->cachedRoot;
        }

        $start = Str::startsWith($root, 'http://') ? 'http://' : 'https://';

        return preg_replace('~'.$start.'~', $scheme, $root, 1);
    }

    /**
     * Set the default named parameters used by the URL generator.
     *
     * @param  array  $defaults
     * @return void
     */
    public function defaults(array $defaults): void
    {
        $this->routeUrl()->defaults($defaults);
    }

     /**
     * Get the default named parameters used by the URL generator.
     *
     * @return array
     */
    public function getDefaultParameters(): array
    {
        return $this->routeUrl()->defaultParameters;
    }
    
    /**
     * Determine if the given path is a valid URL.
     * 
     * @param  string  $path 
     * @return bool
     */
    public function isValidUrl($path): bool
    {
        if (Str::startsWith($path, ['#', '//', 'mailto:', 'tel:', 'sms:', 'http://', 'https://'])) {
            return true;
        }
        
        return filter_var($path, FILTER_VALIDATE_URL) !== false;
    }
    
    /**
     * Get the Route URL generator instance.
     * 
     * @return \Syscodes\Components\Routing\RouteUrlGenerator
     */
    protected function routeUrl()
    {
        if ( ! $this->routeGenerator) {
            $this->routeGenerator = new RouteUrlGenerator($this, $this->request);
        }
        
        return $this->routeGenerator;
    }

    /**
     * Format the given URL segments into a single URL.
     * 
     * @param  string  $root
     * @param  string  $path
     * @param  \Syscodes\Components\Routing\Route|null  $route
     * @return string
     */
    public function format($root, $path, $route = null): string
    {
        $path = '/'.trim($path, '/');

        if ($this->formatHostUsing) {
            $root = call_user_func($this->formatHostUsing, $root, $route);
        }

        if ($this->formatPathUsing) {
            $path = call_user_func($this->formatPathUsing, $path, $route);
        }


        return trim($root.$path, '/');
    }

    /**
     * Set the forced root URL.
     * 
     * @param  string  $root 
     * @return void
     */
    public function forceRootUrl($root): void
    {
        $this->forcedRoot = $root ? rtrim($root, '/') : null;

        $this->cachedRoot = null;
    }

    /**
     * Set the URL origin for all generated asset URLs.
     *
     * @param  string|null  $root 
     * @return void
     */
    public function useAssetOrigin(?string $root): void
    {
        $this->assetRoot = $root ? rtrim($root, '/') : null;
    }

    /**
     * Get the session implementation from the resolver.
     * 
     * @return \Syscodes\Components\Session\Store|null
     */
    protected function getSession()
    {
        if ($this->sessionResolver) {
            return call_user_func($this->sessionResolver);
        }
    }

    /**
     * Set the route collection.
     * 
     * @param  \Syscodes\Components\Routing\Collections\RouteCollection  $routes 
     * @return static
     */
    public function setRoutes(RouteCollection $routes):static
    {
        $this->routes = $routes;
        
        return $this;
    }
    
    /**
     * Set the session resolver for the generator.
     * 
     * @param  callable  $sessionResolver 
     * @return static
     */
    public function setSessionResolver(callable $sessionResolver): static
    {
        $this->sessionResolver = $sessionResolver;
        
        return $this;
    }
    
    /**
     * Set the encryption key resolver.
     * 
     * @param  callable  $keyResolver 
     * @return static
     */
    public function setKeyResolver(callable $keyResolver): static
    {
        $this->keyResolver = $keyResolver;
        
        return $this;
    }
    
    /**
     * Get the root controller namespace.
     * 
     * @return string
     */
    public function getRootControllerNamespace(): string
    {
        return $this->rootNamespace;
    }
    
    /**
     * Set the root controller namespace.
     * 
     * @param  string  $rootNamespace 
     * @return static
     */
    public function setRootControllerNamespace($rootNamespace): static
    {
        $this->rootNamespace = $rootNamespace;
        
        return $this;
    }

    /**
     * Set a callback to be used to format the host of generated URLs.
     *
     * @param  \Closure  $callback
     * @return static
     */
    public function formatHostUsing(Closure $callback): static
    {
        $this->formatHostUsing = $callback;

        return $this;
    }

    /**
     * Set a callback to be used to format the path of generated URLs.
     *
     * @param  \Closure  $callback
     * @return static
     */
    public function formatPathUsing(Closure $callback): static
    {
        $this->formatPathUsing = $callback;

        return $this;
    }

    /**
     * Get the path formatter being used by the URL generator.
     *
     * @return \Closure
     */
    public function pathFormatter()
    {
        return $this->formatPathUsing ?: function ($path) {
            return $path;
        };
    }

    /**
     * Gets the Request instance.
     * 
     * @return \Syscodes\Components\Http\Request
     */
    public function getRequest(): Request
    {
        return $this->request;
    }

    /**
     * Sets the current Request instance.
     * 
     * @param  \Syscodes\Components\Http\Request  $request 
     * @return void
     */
    public function setRequest(Request $request): void
    {
        $this->request = $request;

        $this->cachedRoot = null;
        $this->cachedScheme = null;

        take($this->routeGenerator?->defaultParameters ?: [], function ($defaults) {
            $this->routeGenerator = null;

            if ( ! empty($defaults)) {
                $this->defaults($defaults);
            }
        });
    }
}