<?php

/*
|------------------------------------------------------------------------
| Lenevor Config Class PSR-4                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build psr-4. 
|
| Note: [!!] Do not modify it directly.
|
*/

return [

    'Syscodes\\Components\\' => SYS_PATH.'src'.DIRECTORY_SEPARATOR.'components',
    'Syscodes\\Bundles' => SYS_PATH.'src'.DIRECTORY_SEPARATOR.'bundles',    
    'App\\' => APP_PATH,

];