<?php

/*
|------------------------------------------------------------------------
| Lenevor Config Class PSR-4                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build psr-4. 
|
| Note: [!!] Do not modify it directly.
|
*/

$baseDir = dirname(SYS_PATH);

return [

    'Syscodes\\Components\\Support\\' => [SYS_PATH.'src/components/Macroable', SYS_PATH.'src/components/Collections', SYS_PATH.'src/components/Conditionable'],
    'Syscodes\\Components\\' => SYS_PATH.'src/components',
    'Syscodes\\Bundles\\' => SYS_PATH.'src/bundles',  
    'Database\\Seeders\\' => $baseDir.'/database/seeders', 
    'Database\\Factories\\' => $baseDir.'/database/factories',  
    'App\\' => $baseDir.'/app',

];